### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by igorsantos07**
- added validation and better placeholder to the new entry form, so user's won't forget the protocol or enter bad email addresses
- the top menu now displays the active page properly
- the form also received a proper bootstrap-y markup. However, it still seems badly formatted (see #16)

### CODE REVIEW

**Comment by davidsonfellipe** [comment]
@igorsantos07 Nice guy, I'll look #16

**Comment by igorsantos07** [comment]
I'll try to fix the merge conflicts :)

**Comment by igorsantos07** [comment]
that was fast! :D
great you liked the upgrade :)

**Comment by davidsonfellipe** [comment]
@igorsantos07 thanks!

**Pull request merged**
